### ISSUE TITLE
Enquiry for detailed information about the test dataset

### ISSUE THREAD

**Issue by 0l-hnh** [rtzr/Awesome-Korean-Speech-Recognition#1]
안녕하세요,

본 프로젝트에 STT API 들 성능이 잘 정리돼 있어, 굉장히 유용하게 참고하였습니다.
추후 다른 Open 모델 등의 성능을 제보하고 싶다는 생각도 드는데요, 
기존 측정하신 결과와 공평하게 비교하기 위하여 API 별 에러율을 측정할 때 사용하신 'DB 별 3000 개 파일' 의 정보가 있으면 좋을 것 같습니다.

혹시 해당 테스트 파일 리스트를 공유하실 예정이 있나요?

감사합니다.

**Comment by kimdwkimdw** [comment]
AIHub에서 공개한 포멧이 데이터셋별로 구조가 다 달라서, 원하시는 포멧으로 공개드리기 쉬울지는 모르겠습니다만
각 데이터셋별로 해당하는 오디오파일의 리스트는 공개할 예정입니다.

**Comment by upskyy** [comment]
@0l-hnh  안녕하세요,

평가한 3,000개의 파일 정보를 [docs](https://github.com/rtzr/Awesome-Korean-Speech-Recognition/tree/main/docs)에 넣어 놓았습니다.
도움이 되시면 좋겠습니다.

감사합니다.

**Comment by rezimitpo** [comment]
안녕하세요
한국어 STT 벤치마킹을 잘 정리해주셔서 도움을 많이 받았습니다.

혹시 CER 산출에 사용하신 정답지 및 추론결과도 받아볼 수 있을지 여쭙니다.
감사합니다.

**Comment by kimdwkimdw** [comment]
@rezimitpo
문서에 나와있듯이 데이터셋별로 AIHUB에 가서 직접 다운 받으시면 됩니다.
추론 결과는 별도로 공개하지 않습니다.

**Comment by rezimitpo** [comment]
답변 감사합니다.
데이터셋별로 전사규칙 등도 다르고 일부 데이터들은 익명화 처리(예를 들어 @사람1 등)도 돼있는데 이런 부분들을 어떤 기준으로 평가하셨는지가 궁금했습니다.

채점을 위한 정답지만이라도 공개가 된다면 다른 모델과도 비교해보고 싶어서요.
STT 특성 상 정답지에 따라 성능지표가 실제 성능과 차이가 많을 수 있다고 생각합니다.

**Comment by kimdwkimdw** [comment]
@rezimitpo
데이터셋 별로 일정하게 normalization 규칙이 제공되어 있다면, 일정한 규칙에 의해서 텍스트는 제거되었을 수 있습니다. (모든 모델의 평가에 똑같겟지요.) 규칙이 없다면 정답지 원문을 그대로 사용했습니다.

실제 음성 데이터
```
김철수 가 말했습니다
```

정답지
```
@사람1 가 말했습니다
```

위와 같은 오디오와 정답지가 존재한다면 모든 모델이 같은 방식으로 4개의 문자가 오류로 측정되었습니다.
데이터셋에서 만약 `"@"로 시작하는 단어가 있다면 제거해주세요` 라고 되어있다면 제거해서 3개의 문자가 오류로 측정 되었겠죠.

정답지는 [AIHUB](https://www.aihub.or.kr/aihubdata/data/view.do?currMenu=115&topMenu=100&aihubDataSe=realm&dataSetSn=464)에서 직접 받으시면 됩니다.
AIHUB 규정상 제3자 배포는 허용되지 않습니다.
